import {
  Geist,
  Geist_Mono,
  Inter,
  Roboto,
  Open_Sans,
  Poppins,
  Montserrat,
  Lato,
  Oswald,
  Source_Sans_3,
  Raleway,
  PT_Sans
} from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

// Configure fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable}
          ${inter.variable}
          ${roboto.variable}
          ${openSans.variable}
          ${poppins.variable}
          ${montserrat.variable}
          ${lato.variable}
          antialiased
        `}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}